### ISSUE TITLE
Python27 error

### ISSUE THREAD

**Issue by autistici** [4w4k3/Umbrella#6]
this is my error:

File "/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\Python27\Scripts\pkg_resources\__init__.py", line 48, in <module>
    import six
ImportError: No module named six
Traceback (most recent call last):
  File "umbrella.py", line 239, in <module>
    main()
  File "umbrella.py", line 215, in main
    os.rename('dist/D.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by 4w4k3** [comment]
Wait for final umbrella release

**Comment by autistici** [comment]
I solved by installing manually. the result is a xxx.pdf.exe files! having the final .exe, this tool does not very useful.

**Comment by 4w4k3** [comment]
Try now.
